### PR TITLE
Add basic Outlook text extraction

### PR DESCRIPTION
**Pull request by anthonypuppo**
## Motivation and Context (Why the change? What's the scenario?)
Adds support for extracting text content from Outlook (.msg) documents.

## High level description (Approach, Design)
Uses [MSGReader](https://github.com/Sicos1977/MSGReader) for text extraction.

### CODE REVIEW

**Comment by crickman** [comment]
Thank you for this.

I do wonder if live connection via a plug-in/function might be a more common approach for accessing email.  

I suppose if an important .msg needed to be imported...why not?

**Comment by anthonypuppo** [comment]
> Thank you for this.
> 
> 
> 
> I do wonder if live connection via a plug-in/function might be a more common approach for accessing email.  
> 
> 
> 
> I suppose if an important .msg needed to be imported...why not?

@crickman That would probably be way more ideal from nearly every angle (UX, realtime data, etc). However, a connection to graph might not be high on a team's priority list, so this adds support for those "good for now" cases 😄.

**Comment by dluc** [comment]
Could you address the conflicts please?

Longer term I think we'll add MSGraph, however in many companies MSGraph API is blocked, IMAP too, so it's nice having some solution :-)

**Comment by anthonypuppo** [comment]
Closing due to how stale this branch has gotten.

**Pull request closed without merging**
