### PR TITLE
Add link to MSSQL Server plugin

### PR DESCRIPTION
**Pull request by kbeaugrand**
## Motivation and Context (Why the change? What's the scenario?)

I developped a MSSQL Server connector for Semantic Kernel and also a connector for Kernel Memory.

### CODE REVIEW

**Comment by dluc** [comment]
@kbeaugrand thank you! is the docker image mentioned here https://devblogs.microsoft.com/azure-sql/development-with-sql-in-containers-on-macos going to work to test your extension?

**Comment by dluc** [comment]
I'm trying to test the package, using the docker image from the link above, but something is not working, probably just me, any suggestion?

Start the docker image:
```
docker run -p 1433:1433 --name sql2022 \
    -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Your_Strong.Passw0rd" \
    -it --rm mcr.microsoft.com/mssql/server:2022-latest
```

Connection string: I've tried a few combinations:
```
"Server=localhost,1433;Database=myDatabase;User Id=sa;Password=Your_Strong.Passw0rd;"
"Server=localhost,1433;Database=myDatabase;User Id=mssql;Password=Your_Strong.Passw0rd;"
"Server=127.0.0.1;Database=KM;Trusted_Connection=True;User Id=sa;Password=Your_Strong.Passw0rd;"
"Server=.;Database=KM;Trusted_Connection=True;Password=Your_Strong.Passw0rd;"
"Server=.;Database=KM;Trusted_Connection=True;"
```

The error is always the same:
> A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)

**Comment by DrEight** [comment]
I checked my docker run script and it looks identical apart that I'm saving the database outside the container, adding the switch: -v c:/mysqldatafolder:/var/opt/mssql/data 
With Azure Data storage I use the address 127.0.0.1 but I have the settings: Encrypt = Mandatory (true), Trust Server Certificate = false.
The last setting could be your problem

**Comment by kbeaugrand** [comment]
> @kbeaugrand thank you! is the docker image mentioned here https://devblogs.microsoft.com/azure-sql/development-with-sql-in-containers-on-macos going to work to test your extension?

Yes I'm using this image. 
For the connection string, I have to use those settings: 
```
Server=tcp:localhost,1433;Initial Catalog=master;Persist Security Info=False;User ID=<userId>;Password=<password>;MultipleActiveResultSets=False;TrustServerCertificate=True;Connection Timeout=30;
```

I guess that ```MultipleActiveResultSets``` is not mandatory (an depending on the usage). But ```TrustServerCertificate=True``` is mandatory for you since, you're running a local version of SQL server, and using SLL ciphering with a certificate that you are not owning... 
This is absolutely not related to this plugin, simply the SQL server deployment purpose...

**Comment by dluc** [comment]
thanks for the details, I will give them a try.  Should I use "sa" as a user Id to start, or is there any other default user available after starting the docker image?

**Comment by kbeaugrand** [comment]
> thanks for the details, I will give them a try. Should I use "sa" as a user Id to start, or is there any other default user available after starting the docker image?

Yes, your docker run command line should specify the SA password. So to get started, you should use sa account.
Please find information about using the usage of MSSQL server as docker container at [https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash)

**Comment by dluc** [comment]
@kbeaugrand looks like there's an issue with index names containing the `-` symbol, e.g.

`CreateIndexAsync("172dbdcb-fa44-4356-b561-c0d4663b2914")` leads to an exception: 

```shell
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '-'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
         at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__210_1(IAsyncResult result)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at KernelMemory.MemoryStorage.SqlServer.SqlServerMemory.CreateIndexAsync(String index, Int32 vectorSize, CancellationToken cancellationToken)
```

**Comment by dluc** [comment]
I've added the test suite so you should be able to run them more easily too. Currently all tests are failing, here's a few error messages:
* `A TOP N or FETCH rowcount value may not be negative`
* `Invalid object name 'dbo.SKEmbeddings_87e3e091-ab81-4bc0-a527-f0a4b25b25e3'`
* `Incorrect syntax near '-'`

image

**Comment by kbeaugrand** [comment]
> I've added the test suite so you should be able to run all tests more easily too. Currently all tests are failing, here's a few error messages:
> 
> * `A TOP N or FETCH rowcount value may not be negative`
> * `Invalid object name 'dbo.SKEmbeddings_87e3e091-ab81-4bc0-a527-f0a4b25b25e3'`
> * `Incorrect syntax near '-'`
> 
> image

Thank you @dluc for the functional tests addition ! I released a new version (1.0.3). 

image

After updating the package on the Kernel Memory, this now fixed for all functional tests:

image

Regards,

**Review by dluc — APPROVED** [review]

**Comment by dluc** [comment]
🚀

**Pull request merged**
