### PR TITLE
Fix transaction problem in SQL Server Memory DeleteAsync method

### PR DESCRIPTION
**Pull request by marcominerva**
## Motivation and Context (Why the change? What's the scenario?)
This PR fixes an issue when trying to delete a document from SQL Server Memory.

## High level description (Approach, Design)
The [DeleteDocumentHandler](https://github.com/microsoft/kernel-memory/blob/main/service/Core/Handlers/DeleteDocumentHandler.cs) class calls the memory `GetListAsync` method and then deletes each returned records, using an async enumeration:

https://github.com/microsoft/kernel-memory/blob/2ff894c99d30531fe83a9134c35ec4608583ef59/service/Core/Handlers/DeleteDocumentHandler.cs#L45-L54

The issue is related to how records are returned in [SqlServerMemory.GetListAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L235):

https://github.com/microsoft/kernel-memory/blob/2ff894c99d30531fe83a9134c35ec4608583ef59/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L291-L294

In this code, records are yield inside a **DataReader** loop, so the connection is kept open until the end of the list. As shown above, `DeleteDocumentHandler` calls `DeleteAsync` while iterating on records. In case of SQL Server:

https://github.com/microsoft/kernel-memory/blob/2ff894c99d30531fe83a9134c35ec4608583ef59/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L137-L168

This method tries to open a new connection and execute commands within a transaction. Because it is called while executing [GetListAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L235), there already is an opened connection that is reading data, so it causes a deadlock that ends with a Timeout exception.

This PR fixes the issue modifying the [GetListAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L235) method so that it reads all the data, closes the connection and then returns the list.

### CODE REVIEW

**Comment by dluc** [comment]
@marcominerva I can't reproduce the problem you're describing here. I added a new test here https://github.com/microsoft/kernel-memory/pull/718/files and the test is working fine. Is the test missing something?
I'd like to reproduce the issue before making any change, to be sure the fix works and we won't have future regressions.

**Comment by marcominerva** [comment]
@dluc You need to import at least two documents, then try to delete the first one.

I have created a small repro here: https://github.com/marcominerva/KernelMemorySqlServerIssue

image

Use the first API to upload two different documents, then try to delete the first and you'll obtain a Timeout exception from SQL Server.

**Comment by dluc** [comment]
I merged in the `ItDeletesRecords` test I added in #718. 

The test is failing on my local machine, using MSSQL docker image. Could you take a look?

**Comment by marcominerva** [comment]
@dluc I have just tried the `ItDeletesRecords` test on this `sqlserver-disposefix` branch and on my machine it passes correctly (I'm using a LocalDB instance). What kind of failure do you encounter?

**Comment by dluc** [comment]
Getting a timeout exception on batch upserts. Could you try the run-mssql.sh script which runs the docker image?

**Comment by marcominerva** [comment]
Tried with the container created by `run-mssql.sh`, but still works correctly. It sounds strange that you get a timeout exception on batch upserts (so, you stop before the delete), because upserts don't call [GetListAsync](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer/SqlServerMemory.cs#L235), that it the only method I have modified. I have also tried to set the `MemoryDbUpsertBatchSize` explicitly in [DefaultTests](https://github.com/microsoft/kernel-memory/blob/main/extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs).cs:

```csharp
this._memory = builder
    .With(new KernelMemoryConfig
    {
        DefaultIndexName = "default4tests",
        DataIngestion = new()
        {
            MemoryDbUpsertBatchSize = 64
        }
    })
```

Do other SQL Server tests work on your local machine?

**Comment by dluc** [comment]
> Do other SQL Server tests work on your local machine?

some other tests are failing, I'm starting to think if it's a problem with docker and macOS.

On `main` branch:

image

On this PR branch:

Execution 1

image

Execution 2, after restarting the docker image:

image

## Execution 1 log

```
Microsoft.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is no...

Microsoft.Data.SqlClient.SqlException
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext() in km/extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 533
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext() in km/extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 543
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken) in km/extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 435
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken) in km/extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 435
   at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveRecordAsync(DataPipeline pipeline, IMemoryDb db, MemoryRecord record, HashSet`1 createdIndexes, CancellationToken cancellationToken) in km/service/Core/Handlers/SaveRecordsHandler.cs:line 266
   at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken) in km/service/Core/Handlers/SaveRecordsHandler.cs:line 214
   at Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken) in km/service/Core/Pipeline/InProcessPipelineOrchestrator.cs:line 174
   at Microsoft.KernelMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, IContext context, CancellationToken cancellationToken) in km/service/Core/Pipeline/BaseOrchestrator.cs:line 121
   at Microsoft.KM.Core.FunctionalTests.DefaultTestCases.RecordDeletionTest.ItDeletesRecords(IKernelMemory memory, IMemoryDb db, Action`1 log) in km/service/tests/Core.FunctionalTests/DefaultTestCases/RecordDeletionTest.cs:line 30
   at Microsoft.SQLServer.FunctionalTests.DefaultTests.ItDeletesRecords() in km/extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs:line 119
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)

System.ComponentModel.Win32Exception
Unknown error: 258
  Exception doesn't have a stacktrace
```

## Execution 2 log

```
Microsoft.Data.SqlClient.SqlException: Transaction (Process ID 73) was deadlocked on communication buffer resources with another process and has been ...

Microsoft.Data.SqlClient.SqlException
Transaction (Process ID 73) was deadlocked on communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext() in km//extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 533
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext() in km//extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 543
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken) in km//extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 435
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken) in km//extensions/SQLServer/SQLServer/SqlServerMemory.cs:line 435
   at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveRecordAsync(DataPipeline pipeline, IMemoryDb db, MemoryRecord record, HashSet`1 createdIndexes, CancellationToken cancellationToken) in km//service/Core/Handlers/SaveRecordsHandler.cs:line 266
   at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken) in km//service/Core/Handlers/SaveRecordsHandler.cs:line 214
   at Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken) in km//service/Core/Pipeline/InProcessPipelineOrchestrator.cs:line 174
   at Microsoft.KernelMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, IContext context, CancellationToken cancellationToken) in km//service/Core/Pipeline/BaseOrchestrator.cs:line 121
   at Microsoft.KM.Core.FunctionalTests.DefaultTestCases.RecordDeletionTest.ItDeletesRecords(IKernelMemory memory, IMemoryDb db, Action`1 log) in km//service/tests/Core.FunctionalTests/DefaultTestCases/RecordDeletionTest.cs:line 30
   at Microsoft.SQLServer.FunctionalTests.DefaultTests.ItDeletesRecords() in km//extensions/SQLServer/SQLServer.FunctionalTests/DefaultTests.cs:line 119
   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)
```

**Review by dluc — APPROVED** [review]
Tested with MSSQL 2019 docker image (vs 2022), and all tests are passing.

**Pull request merged**
